"""baseline schema

Revision ID: 96ea1280ee3c
Revises: 
Create Date: 2026-06-21 21:35:48.552732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ea1280ee3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_sessions',
    sa.Column('draw_id', sa.Text(), nullable=False),
    sa.Column('root_run_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=False),
    sa.Column('source_checkpoint_id', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('requested_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diversity', sa.Text(), server_default='medium', nullable=False),
    sa.Column('mode', sa.Text(), server_default='batch_draw', nullable=False),
    sa.Column('group_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('card_run_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('winner_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('draw_id')
    )
    with op.batch_alter_table('draw_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_draw_root', ['root_run_id'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_entity', ['entity_type', 'entity_id', 'event_id'], unique=False)
        batch_op.create_index('idx_events_ts', ['entity_type', 'ts'], unique=False)

    op.create_table('fusion_plans',
    sa.Column('fusion_id', sa.Text(), nullable=False),
    sa.Column('root_run_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=False),
    sa.Column('base_run_id', sa.Text(), server_default='', nullable=False),
    sa.Column('source_run_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('draw_session_id', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('composite_target_artifact_id', sa.Text(), nullable=True),
    sa.Column('output_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('fusion_id')
    )
    with op.batch_alter_table('fusion_plans', schema=None) as batch_op:
        batch_op.create_index('idx_fusion_root', ['root_run_id'], unique=False)

    op.create_table('preference_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.Float(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('default_locks', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('positive_preferences', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('negative_preferences', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('preferred_variant_labels', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('score_drop_tolerance_hint', sa.Float(), server_default='0.02', nullable=False),
    sa.Column('summary_source_event_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('id = 1', name='ck_pref_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('root_run_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('source_checkpoint_id', sa.Text(), nullable=True),
    sa.Column('source_checkpoint_label', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('run_dir', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('favorite', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('variant_group_id', sa.Text(), nullable=True),
    sa.Column('variant_index', sa.Integer(), nullable=True),
    sa.Column('variant_label', sa.Text(), nullable=True),
    sa.Column('draw_session_id', sa.Text(), nullable=True),
    sa.Column('draw_card_index', sa.Integer(), nullable=True),
    sa.Column('replacement_of_run_id', sa.Text(), nullable=True),
    sa.Column('fusion_id', sa.Text(), nullable=True),
    sa.Column('base_run_id', sa.Text(), nullable=True),
    sa.Column('source_run_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('idx_runs_created', ['created_at'], unique=False)
        batch_op.create_index('idx_runs_draw', ['draw_session_id'], unique=False)
        batch_op.create_index('idx_runs_fav', ['favorite'], unique=False, sqlite_where=sa.text('favorite = 1'))
        batch_op.create_index('idx_runs_fusion', ['fusion_id'], unique=False)
        batch_op.create_index('idx_runs_parent', ['parent_run_id'], unique=False)
        batch_op.create_index('idx_runs_root', ['root_run_id'], unique=False)
        batch_op.create_index('idx_runs_score', ['final_score'], unique=False)
        batch_op.create_index('idx_runs_status', ['status'], unique=False)
        batch_op.create_index('idx_runs_vgroup', ['variant_group_id'], unique=False)

    op.create_table('variant_groups',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('root_run_id', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=False),
    sa.Column('source_checkpoint_id', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), server_default='', nullable=False),
    sa.Column('mode', sa.Text(), server_default='', nullable=False),
    sa.Column('variant_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diversity', sa.Text(), server_default='medium', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('child_run_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('winner_run_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.Column('draw_session_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    with op.batch_alter_table('variant_groups', schema=None) as batch_op:
        batch_op.create_index('idx_vg_draw', ['draw_session_id'], unique=False)
        batch_op.create_index('idx_vg_root', ['root_run_id'], unique=False)

    op.create_table('fusion_regions',
    sa.Column('fusion_id', sa.Text(), nullable=False),
    sa.Column('region_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), server_default='', nullable=False),
    sa.Column('source_run_id', sa.Text(), server_default='', nullable=False),
    sa.Column('instruction', sa.Text(), server_default='', nullable=False),
    sa.Column('geometry_type', sa.Text(), server_default='rect', nullable=False),
    sa.Column('geometry', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('strength', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('blend_mode', sa.Text(), server_default='soft', nullable=False),
    sa.Column('feather', sa.Float(), server_default='0.08', nullable=False),
    sa.ForeignKeyConstraint(['fusion_id'], ['fusion_plans.fusion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fusion_id', 'region_id', name='pk_fusion_regions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fusion_regions')
    with op.batch_alter_table('variant_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_vg_root')
        batch_op.drop_index('idx_vg_draw')

    op.drop_table('variant_groups')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('idx_runs_vgroup')
        batch_op.drop_index('idx_runs_status')
        batch_op.drop_index('idx_runs_score')
        batch_op.drop_index('idx_runs_root')
        batch_op.drop_index('idx_runs_parent')
        batch_op.drop_index('idx_runs_fusion')
        batch_op.drop_index('idx_runs_fav', sqlite_where=sa.text('favorite = 1'))
        batch_op.drop_index('idx_runs_draw')
        batch_op.drop_index('idx_runs_created')

    op.drop_table('runs')
    op.drop_table('preference_profile')
    with op.batch_alter_table('fusion_plans', schema=None) as batch_op:
        batch_op.drop_index('idx_fusion_root')

    op.drop_table('fusion_plans')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_ts')
        batch_op.drop_index('idx_events_entity')

    op.drop_table('events')
    with op.batch_alter_table('draw_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_draw_root')

    op.drop_table('draw_sessions')
    # ### end Alembic commands ###
